### ISSUE TITLE
Some packages (at least HHVM) being built from branches instead of tags

### ISSUE THREAD

**Issue by fredemmott** [sbagmeijer/ulyaoth#4]
A branch is not a release - it is a moving target.

The package you are calling '3.7.4' is currently 3.7.3 + this one commit: https://github.com/facebook/hhvm/commit/7061b209b66d6b6c522bdcfc6c10745561239509

3.7.4 does not yet exist.

That commit is not yet in any release; when it is, there will be a follow-up commit removing the -dev.

This also means that it's likely that your '3.7.3' package is actually 3.7.2 + a version number change.

Please build from tagged releases instead of branches.

**Comment by sbagmeijer** [comment]
Are this all the correct tagged versions?:

https://github.com/facebook/hhvm/tags

**Comment by fredemmott** [comment]
Yep. For what it's worth, this isn't HHVM-specific - it's likely to be a problem with other packages here.

**Comment by sbagmeijer** [comment]
Thanks @fredemmott I resolved the build script now so the hhvm packages are build from tags now and have removed the incorrect version. Will add a warning on my forum to inform people that previous builds could have been experimental.

**Comment by sbagmeijer** [comment]
Just double checking all other packages in repository:

Hiawatha: Looks fine build from official tar.gz.
httpdiff: Looks fine package is correctly named that it are master builds.
Kibana: Looks fine build from official tar.gz.
mbedtls: Looks fine build from official tar.gz.
monkey: Looks fine build from official tar.gz.
nginx-modsecurity: Looks fine build from official tar.gz.
nginx-naxsi: Looks fine correct named that it are master builds.
nginx-pagespeed: Look fine build from their release zip files.
nginx-passenger: Looks fine build from official tar.gz.
nginx: Looks fine build from official tar.gz.
solr: Looks fine build from official tar.gz.
tomcat: Looks fine build from official tar.gz.
tomcat-native: Looks fine build from official tar.gz.
tengine: Looks fine build from official tar.gz.
logstash-forwarder: Looks fine package is correctly named that it are master builds.
banana: Looks fine build from their "release" branch according to their documentation.
spotify: build from their official debian package.

Looks only one wrong was hhvm.

**Comment by sbagmeijer** [comment]
Created now:
3.7.3-2 
3.6.5
3.3.7

So all version in the repository should have a correct version from a tag.

hhvm --version
HipHop VM 3.7.3 (rel)
Compiler: tags/HHVM-3.7.3-0-g08c64d25f6c2cd316730b1d37db9eb33744cb306
Repo schema: 6ba408ef27e1fc7820c8bd6352989f40c1acb812

rpms should be available tonight.
