### ISSUE TITLE
Banana v1.5.0 package is not necessarily v1.5.0

### ISSUE THREAD

**Issue by fredemmott** [sbagmeijer/ulyaoth#5]
While banana's documentation says to pull the release branch, it does not say that it will only contain commits that are in releases.

 - their latest release is v1.5.0, which is https://github.com/LucidWorks/banana/commit/03848000b49c4e84fd5b6e18b1149fcd59796503
 - their 'release' branch contains additional commits (I'm guessing for a future 1.5.1 or 1.6.0), and is currently https://github.com/LucidWorks/banana/commit/010b861333b09c6faef620202b073df84b5f81b1
 - the *current* list of differences between banana 1.5.0 and 'release' branch is here: https://github.com/LucidWorks/banana/compare/v1.5.0...release

Related: #4

**Comment by sbagmeijer** [comment]
Thank you @fredemmott for taking the time to explain it,

I now understand what to look at to avoid this from happening again for any future packages.

I fixed this package also now and a new "1.5.0-2" version is released tonight.

**Comment by sbagmeijer** [comment]
Changed logstash-forwarder also to use a stable version  now I understand how those tags work.

**Comment by sbagmeijer** [comment]
Created a rpms with stable version of Naxsi also build from released tar.gz file.

**Comment by sbagmeijer** [comment]
Again thank you @fredemmott for reporting and explaining.
I now updated all packages and removed all the old once so people won't install them again.
